version: '3.5'
services:
    influxdb:
        image: influxdb:1.8.1-alpine
        hostname: influxdb
        container_name: influxdb
        environment:
            INFLUXDB_DB: bookit
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: admin
        ports:
            - "8086:8086"

    grafana:
        image: grafana/grafana:7.1.0
        hostname: grafana
        container_name: grafana
        volumes: 
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        environment:
            GF_INSTALL_PLUGINS: citilogics-geoloop-panel
        ports:
            - "3000:3000"
  
    geojson:
        build: ./geojson
        hostname: geojson
        container_name: geojson
        ports:
            - "4000:4000"

    # Just for debug purpose
    chronograf:
        image: chronograf:1.8-alpine
        ports:
            - 8888:8888
        command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
