apiVersion: 1

deleteDatasources:
    - name: Graphite
      orgId: 1
      
datasources:
    - name: influxdb
      isDefault: true
      type: influxdb
      access: proxy
      database: bookit
      user: admin
      url: http://influxdb:8086
      jsonData:
          timeInterval: "15s"
      secureJsonData:
          password: admin