{
 "title": "BookIT",
 "time": { "from": "2020-07-24T06:00:00.000Z", "to": "2020-07-24T15:00:00.000Z" },
 "panels": [
  {
   "title": "#Parcels: scheduled vs delivered",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#Parcels" }
   ],
   "targets": [
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "schedule",
     "select": [
      [
       { "params": [ "height" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Delivered",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "live_tracking",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "delivered" }
     ]
    }
   ]
  },
  {
   "title": "Delivered / Scheduled",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "scheduled",
     "measurement": "schedule",
     "select": [
      [
       { "params": [ "packages" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "delivered",
     "measurement": "live_tracking",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "delivered" }
     ]
    }
   ]
  },
  {
   "title": "# Percels Scheduled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "schedule",
     "select": [
      [
       { "params": [ "packages" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Percels Delivered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "live_tracking",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "delivered" }
     ]
    }
   ]
  },
  {
   "title": "Motivations for delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "# Times" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "motivation" ], "type": "tag" }
     ],
     "measurement": "live_tracking",
     "query": "SELECT count(\"delay\") FROM \"live_tracking\" WHERE (\"status\" = 'delay') AND $timeFilter GROUP BY \"motivation\" ",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "delay" },
      { "condition": "AND", "key": "event", "operator": "!=", "value": "delivered" },
      { "condition": "AND", "key": "event", "operator": "!=", "value": "not_delivered" }
     ]
    }
   ]
  },
  {
   "title": "Localization Map",
   "type": "citilogics-geoloop-panel",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "live_tracking",
     "query": "SELECT \"delay\" 60 - FROM \"live_tracking\" WHERE $timeFilter GROUP BY time(5m), \"location\" fill(0)",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * (-1) + 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Motivations for not delivered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "# Times" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "motivation" ], "type": "tag" }
     ],
     "measurement": "live_tracking",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "not_delivered" }
     ]
    }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 24 },
   "options": {
    "content": "<img src=\"https://github.com/emanuele-falzone/drviz/raw/project/images/map-legend-horizzontal.png\">"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}